/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as OsRouteImport } from './routes/os'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as IzeteRouteImport } from './routes/izete'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotasFotografarRouteImport } from './routes/notas.fotografar'
import { Route as ComprasMercadoRouteImport } from './routes/compras.mercado'

const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const OsRoute = OsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const IzeteRoute = IzeteRouteImport.update({
  id: '/izete',
  path: '/izete',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasFotografarRoute = NotasFotografarRouteImport.update({
  id: '/fotografar',
  path: '/fotografar',
  getParentRoute: () => NotasRoute,
} as any)
const ComprasMercadoRoute = ComprasMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => ComprasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRouteWithChildren
  '/config': typeof ConfigRoute
  '/financas': typeof FinancasRoute
  '/instalar': typeof InstalarRoute
  '/izete': typeof IzeteRoute
  '/mais': typeof MaisRoute
  '/notas': typeof NotasRouteWithChildren
  '/os': typeof OsRoute
  '/pets': typeof PetsRoute
  '/compras/mercado': typeof ComprasMercadoRoute
  '/notas/fotografar': typeof NotasFotografarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRouteWithChildren
  '/config': typeof ConfigRoute
  '/financas': typeof FinancasRoute
  '/instalar': typeof InstalarRoute
  '/izete': typeof IzeteRoute
  '/mais': typeof MaisRoute
  '/notas': typeof NotasRouteWithChildren
  '/os': typeof OsRoute
  '/pets': typeof PetsRoute
  '/compras/mercado': typeof ComprasMercadoRoute
  '/notas/fotografar': typeof NotasFotografarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compras': typeof ComprasRouteWithChildren
  '/config': typeof ConfigRoute
  '/financas': typeof FinancasRoute
  '/instalar': typeof InstalarRoute
  '/izete': typeof IzeteRoute
  '/mais': typeof MaisRoute
  '/notas': typeof NotasRouteWithChildren
  '/os': typeof OsRoute
  '/pets': typeof PetsRoute
  '/compras/mercado': typeof ComprasMercadoRoute
  '/notas/fotografar': typeof NotasFotografarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compras'
    | '/config'
    | '/financas'
    | '/instalar'
    | '/izete'
    | '/mais'
    | '/notas'
    | '/os'
    | '/pets'
    | '/compras/mercado'
    | '/notas/fotografar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compras'
    | '/config'
    | '/financas'
    | '/instalar'
    | '/izete'
    | '/mais'
    | '/notas'
    | '/os'
    | '/pets'
    | '/compras/mercado'
    | '/notas/fotografar'
  id:
    | '__root__'
    | '/'
    | '/compras'
    | '/config'
    | '/financas'
    | '/instalar'
    | '/izete'
    | '/mais'
    | '/notas'
    | '/os'
    | '/pets'
    | '/compras/mercado'
    | '/notas/fotografar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprasRoute: typeof ComprasRouteWithChildren
  ConfigRoute: typeof ConfigRoute
  FinancasRoute: typeof FinancasRoute
  InstalarRoute: typeof InstalarRoute
  IzeteRoute: typeof IzeteRoute
  MaisRoute: typeof MaisRoute
  NotasRoute: typeof NotasRouteWithChildren
  OsRoute: typeof OsRoute
  PetsRoute: typeof PetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/os': {
      id: '/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof OsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/izete': {
      id: '/izete'
      path: '/izete'
      fullPath: '/izete'
      preLoaderRoute: typeof IzeteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas/fotografar': {
      id: '/notas/fotografar'
      path: '/fotografar'
      fullPath: '/notas/fotografar'
      preLoaderRoute: typeof NotasFotografarRouteImport
      parentRoute: typeof NotasRoute
    }
    '/compras/mercado': {
      id: '/compras/mercado'
      path: '/mercado'
      fullPath: '/compras/mercado'
      preLoaderRoute: typeof ComprasMercadoRouteImport
      parentRoute: typeof ComprasRoute
    }
  }
}

interface ComprasRouteChildren {
  ComprasMercadoRoute: typeof ComprasMercadoRoute
}

const ComprasRouteChildren: ComprasRouteChildren = {
  ComprasMercadoRoute: ComprasMercadoRoute,
}

const ComprasRouteWithChildren =
  ComprasRoute._addFileChildren(ComprasRouteChildren)

interface NotasRouteChildren {
  NotasFotografarRoute: typeof NotasFotografarRoute
}

const NotasRouteChildren: NotasRouteChildren = {
  NotasFotografarRoute: NotasFotografarRoute,
}

const NotasRouteWithChildren = NotasRoute._addFileChildren(NotasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprasRoute: ComprasRouteWithChildren,
  ConfigRoute: ConfigRoute,
  FinancasRoute: FinancasRoute,
  InstalarRoute: InstalarRoute,
  IzeteRoute: IzeteRoute,
  MaisRoute: MaisRoute,
  NotasRoute: NotasRouteWithChildren,
  OsRoute: OsRoute,
  PetsRoute: PetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
