/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComprasMercadoRouteImport } from './routes/compras.mercado'

const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasMercadoRoute = ComprasMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => ComprasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRouteWithChildren
  '/financas': typeof FinancasRoute
  '/instalar': typeof InstalarRoute
  '/mais': typeof MaisRoute
  '/notas': typeof NotasRoute
  '/compras/mercado': typeof ComprasMercadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compras': typeof ComprasRouteWithChildren
  '/financas': typeof FinancasRoute
  '/instalar': typeof InstalarRoute
  '/mais': typeof MaisRoute
  '/notas': typeof NotasRoute
  '/compras/mercado': typeof ComprasMercadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compras': typeof ComprasRouteWithChildren
  '/financas': typeof FinancasRoute
  '/instalar': typeof InstalarRoute
  '/mais': typeof MaisRoute
  '/notas': typeof NotasRoute
  '/compras/mercado': typeof ComprasMercadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compras'
    | '/financas'
    | '/instalar'
    | '/mais'
    | '/notas'
    | '/compras/mercado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compras'
    | '/financas'
    | '/instalar'
    | '/mais'
    | '/notas'
    | '/compras/mercado'
  id:
    | '__root__'
    | '/'
    | '/compras'
    | '/financas'
    | '/instalar'
    | '/mais'
    | '/notas'
    | '/compras/mercado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComprasRoute: typeof ComprasRouteWithChildren
  FinancasRoute: typeof FinancasRoute
  InstalarRoute: typeof InstalarRoute
  MaisRoute: typeof MaisRoute
  NotasRoute: typeof NotasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras/mercado': {
      id: '/compras/mercado'
      path: '/mercado'
      fullPath: '/compras/mercado'
      preLoaderRoute: typeof ComprasMercadoRouteImport
      parentRoute: typeof ComprasRoute
    }
  }
}

interface ComprasRouteChildren {
  ComprasMercadoRoute: typeof ComprasMercadoRoute
}

const ComprasRouteChildren: ComprasRouteChildren = {
  ComprasMercadoRoute: ComprasMercadoRoute,
}

const ComprasRouteWithChildren =
  ComprasRoute._addFileChildren(ComprasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComprasRoute: ComprasRouteWithChildren,
  FinancasRoute: FinancasRoute,
  InstalarRoute: InstalarRoute,
  MaisRoute: MaisRoute,
  NotasRoute: NotasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
